apiVersion: v1
kind: Service
metadata:
  name: cc-bd 
  #cc_bd doesn't fit kubernetes naming conventions
spec:
  selector:
    app: cc-bd
  ports:
    - port: 5000
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-bd
spec:
  selector:
    matchLabels:
      app: cc-bd
  template:
    metadata:
      labels:
        app: cc-bd
    spec:
      containers:
        - name: cc-bd
          image: yd2696/cc_bd #your-flask-app-image:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/your-database"
